<footer id="footer" class="landing-bunting font-e3">
  <div class="inner">
    <div id="footer-some-docs">
        <a href="/terms_conditions.html" class="footer-doc-link" >Terms & Conditions</a>
        <a href="/privacy.html" class="footer-doc-link" >Privacy</a>
        <a href="/end-user-license-agreement.html" class="footer-doc-link" >License Agreement</a>
    </div>
    <div id="footer-copyright">
       <a href="" > Copyright &copy; {{ moment(Date.now()).year() }} {{ config.author }}. All rights reserved. </a>
    </div>
    <div id="footer-links">
      {# <a href="http://weibo.com/{{ config.weibo }}" class="footer-link" target="_blank" rel="nofollow me noopener noreferrer" ><i class="fa fa-weibo"></i></a> #}
      <a href="https://twitter.com/{{ config.twitter }}" class="footer-link" target="_blank" rel="nofollow me noopener noreferrer" ><i class="fa fa-twitter"></i></a>
      {# <a href="https://github.com/{{ config.github }}" class="footer-link" target="_blank" rel="nofollow me noopener noreferrer" ><i class="fa fa-github-alt"></i></a> #}
      <a href="https://www.facebook.com/{{ config.facebook }}" class="footer-link" target="_blank" rel="nofollow me noopener noreferrer" ><i class="fa fa-facebook"></i></a>
      <a href="https://www.youtube.com/{{ config.youtube }}" class="footer-link" target="_blank" rel="nofollow me noopener noreferrer" ><i class="fa fa-youtube"></i></a>
      <a href="https://www.instagram.com/{{ config.instagram }}" class="footer-link" target="_blank" rel="nofollow me noopener noreferrer" ><i class="fa fa-instagram"></i></a>
    </div>
  </div>
</footer>
