<header id="banner" class="wrapper">
  <div class="inner">
    <div class="inner-wrap">
      <h2 id="banner-title">{{ page.title }}</h2>
    </div>
  </div>
</header>

<div class="class-content-wrap">
  <div class="wrapper">
    <div class="inner">
      {{ page.content }}
    </div>
  </div>
</div>

<div class="class-content-wrap">
  <div class="inner">
    <div class="inner-wrap landing-bunting">
      <div class="intro-sub-content-wrap">
      </div>
    </div>
  </div>
</div>
