<header id="banner" class="wrapper">
  <div class="inner">
    <div class="inner-wrap">
      <h2 id="banner-title">Welcome to Support Center</h2>
      <div id="banner-start">
        <a id="banner-start-link" href="https://gitter.im/Gmagon/support" target="_blank">Online Support Center</a>
      </div>
    </div>  
  </div>
</header>

<div id="content-wrap">
  <div class="container-support">
  </div>
</div>
