- name: Multimedia
  description: Multimedia tools
  list:
    - name: TryToMp3
      appID: com.romanysoft.app.macos.TryToMp3
      description: Index generator plus for Hexo, including new order attributes like top and updateDate.
      link: /products/store/trytomp3/
      preview: /products/store/trytomp3/
      tags:
        - Mp3
        - Audio

    - name: TryToMp3
      appID: com.romanysoft.app.macos.TryToMp3
      description: Index generator plus for Hexo, including new order attributes like top and updateDate.
      link: https://github.com/YuyingWu/hexo-generator-index-plus
      tags:
        - Mp3
        - Audio

    - name: TryToMp3
      appID: com.romanysoft.app.macos.TryToMp3
      description: Index generator plus for Hexo, including new order attributes like top and updateDate.
      link: https://github.com/YuyingWu/hexo-generator-index-plus
      tags:
        - Mp3
        - Audio

    - name: TryToMp3
      appID: com.romanysoft.app.macos.TryToMp3
      description: Index generator plus for Hexo, including new order attributes like top and updateDate.
      link: /products/store/trytomp3/
      tags:
        - Mp3
        - Audio

- name: Utility
  description: Utility tools
  list:
    - name: TryToMp3
      appID: com.romanysoft.app.macos.TryToMp3
      description: Index generator plus for Hexo, including new order attributes like top and updateDate.
      link: /products/store/trytomp3/
      tags:
        - Mp3
        - Audio

    - name: TryToMp3
      appID: com.romanysoft.app.macos.TryToMp3
      description: Index generator plus for Hexo, including new order attributes like top and updateDate.
      link: /products/store/trytomp3/
      tags:
        - Mp3
        - Audio


- name: Office
  description: Office tools
  list:
    - name: TryToMp3
      appID: com.romanysoft.app.macos.TryToMp3
      description: Index generator plus for Hexo, including new order attributes like top and updateDate.
      link: /products/store/trytomp3/
      tags:
        - Office
        - Mp3
        - Audio

    - name: TryToMp3
      appID: com.romanysoft.app.macos.TryToMp3
      description: Index generator plus for Hexo, including new order attributes like top and updateDate.
      link: /products/store/trytomp3/
      tags:
        - Mp3
        - Audio
