- name: Utilities
  description: Utilities support
  list:
    - name: Gmagon Gif
      appID: com.gmagon.app.macos.gmagongif
      description: It is designed to convert the Gif image format to APNG(.png)
      link: /products/store/gmagon_gif/
      preview: /products/store/gmagon_gif/
      tags:
        - Gif
        - Convert
        - Image
        - APNG

    - name: NetworkEyes
      appID: com.romanysoft.app.macos.NetworkEyes
      description: It is is a network monitoring tool for Mac OS.
      link: /products/store/networkeyes/
      preview: /products/store/networkeyes/
      tags:
        - network
        - monitor
        - bandwidth
    
 
- name: Games
  description: Games
  list:
    - name: SudokuMM
      appID: com.romanysoft.app.macos.game.SudokuMM
      description: Enjoy a clear and classic Sudoku game online with your Mac.
      link: /products/store/sudokumm/
      preview: /products/store/sudokumm/
      tags:
        - Game
        - Sudo
        
- name: Multimedia
  description: Multimedia tools
  list:
    - name: TryToMP3
      appID: com.romanysoft.app.macos.TryToMp3
      description: It's easy to convert other formats to MP3(.mp3)
      link: /products/store/trytomp3/
      preview: /products/store/trytomp3/
      tags:
        - MP3
        - Convert
        - Audio

    - name: TryToAAC
      appID: com.romanysoft.app.macos.TryToAAC
      description: It's easy to convert other formats to AAC(.aac)
      link: /products/store/trytoaac/
      preview: /products/store/trytoaac/
      tags:
        - AAC
        - Convert
        - Audio

    - name: TryToWMA
      appID: com.romanysoft.app.macos.TryToWMA
      description: It's easy to convert other formats to WMA(.wma)
      link: /products/store/trytowma/
      preview: /products/store/trytowma/
      tags:
        - WMA
        - Convert
        - Audio

    - name: TryToFLAC
      appID: com.romanysoft.app.macos.TryToFLAC
      description: It's easy to convert other formats to FLAC(.flac)
      link: /products/store/trytoflac/
      preview: /products/store/trytoflac/
      tags:
        - FLAC
        - Convert
        - Audio
        - Lossless Audio
 
    - name: TryToAMR
      appID: com.romanysoft.app.macos.TryToAMR
      description: It's easy to convert other formats to AMR(.amr)
      link: /products/store/trytoamr/
      preview: /products/store/trytoamr/
      tags:
        - AMR
        - Convert
        - Audio

