- name: Utilities
  description: Utilities support
  list:
    - name: Gmagon Gif
      appID: com.gmagon.app.macos.gmagongif
      thumbType: gif
      description: It is a multifunctional GIF tool including converter and gallery. 
      link: /products/store/gmagon_gif/
      preview: /products/store/gmagon_gif/
      tags:
        - Gif
        - Convert
        - Image
        - APNG

    - name: NetworkEyes
      appID: com.romanysoft.app.macos.NetworkEyes
      thumbType: png
      description: It is a network monitoring tool for Mac OS.
      link: /products/store/networkeyes/
      preview: /products/store/networkeyes/
      tags:
        - network
        - monitor
        - bandwidth

    - name: ColorPicker2
      appID: com.romanysoft.app.macos.ColorPicker2
      thumbType: gif
      description: It is a graphical user interface utility for users to select colors
      link: /products/store/colorpicker2/
      preview: /products/store/colorpicker2/
      tags:
        - color
        - picker
        - design
        - graphic

    - name: EasyPing
      appID: com.romanysoft.app.macos.EasyPing
      thumbType: gif
      description: It is a network tool to test whether a particular host is reachable across an IP network. 
      link: /products/store/easyping/
      preview: /products/store/easyping/
      tags:
        - ping
        - network
        - monitor
        - connection

    - name: APNGToGifConverter
      appID: com.gmagon.app.macos.apngtogifconverter
      thumbType: gif
      description: It is a minimum converter to convert APNG to GIF. 
      link: /products/store/apngtogifconverter/
      preview: /products/store/apngtogifconverter/
      tags:
        - Gif
        - Convert
        - Image
        - APNG
    
    - name: XLS2csv
      appID: com.gmagon.app.macos.xls2csv
      thumbType: gif
      description: It is a file converter that converts the XLS/XLSX format to CSV. 
      link: /products/store/xls2csv/
      preview: /products/store/xls2csv/
      tags:
        - xlsx
        - xls
        - csv
        - excel
        - convert

    - name: Gmagon CSS Maker
      appID: com.gmagon.app.macos.gmagoncssmaker
      thumbType: gif
      description: It is a fabulous CSS designer on Mac. 
      link: /products/store/gmagon_css_maker/
      preview: /products/store/gmagon_css_maker/
      tags:
        - css
        - css generator
        - css designer
        - web design

        
 
- name: Games
  description: Games
  list:
    - name: SudokuMM
      appID: com.romanysoft.app.macos.game.SudokuMM
      thumbType: gif
      description: Enjoy a clear and classic Sudoku game online with your Mac.
      link: /products/store/sudokumm/
      preview: /products/store/sudokumm/
      tags:
        - Game
        - Sudoku
        
- name: Multimedia
  description: Multimedia tools
  list:
    - name: TryToMP3
      appID: com.romanysoft.app.macos.TryToMp3
      thumbType: png
      description: It's easy to convert other formats to MP3(.mp3)
      link: /products/store/trytomp3/
      preview: /products/store/trytomp3/
      tags:
        - MP3
        - Convert
        - Audio

    - name: TryToAAC
      appID: com.romanysoft.app.macos.TryToAAC
      thumbType: png
      description: It's easy to convert other formats to AAC(.aac)
      link: /products/store/trytoaac/
      preview: /products/store/trytoaac/
      tags:
        - AAC
        - Convert
        - Audio

    - name: TryToWMA
      appID: com.romanysoft.app.macos.TryToWMA
      thumbType: png
      description: It's easy to convert other formats to WMA(.wma)
      link: /products/store/trytowma/
      preview: /products/store/trytowma/
      tags:
        - WMA
        - Convert
        - Audio

    - name: TryToFLAC
      appID: com.romanysoft.app.macos.TryToFLAC
      thumbType: png
      description: It's easy to convert other formats to FLAC(.flac)
      link: /products/store/trytoflac/
      preview: /products/store/trytoflac/
      tags:
        - FLAC
        - Convert
        - Audio
        - Lossless Audio
 
    - name: TryToAMR
      appID: com.romanysoft.app.macos.TryToAMR
      thumbType: png
      description: It's easy to convert other formats to AMR(.amr)
      link: /products/store/trytoamr/
      preview: /products/store/trytoamr/
      tags:
        - AMR
        - Convert
        - Audio

